import 'package:flutter/material.dart';
import '../../presentation/screens/splash_screen.dart';
import '../../presentation/screens/auth/login_screen.dart';
import '../../presentation/screens/auth/register_screen.dart';
import '../../presentation/screens/home_screen.dart';
import '../../presentation/screens/dashboard/dashboard_screen.dart';
import '../../presentation/screens/accounts/chart_of_accounts_screen.dart';
import '../../presentation/screens/accounts/create_account_screen.dart';
import '../../presentation/screens/accounts/voucher_screen.dart';
import '../../presentation/screens/accounts/create_voucher_screen.dart';
import '../../presentation/screens/customers/customer_list_screen.dart';
import '../../presentation/screens/customers/customer_detail_screen.dart';
import '../../presentation/screens/suppliers/supplier_list_screen.dart';
import '../../presentation/screens/suppliers/supplier_detail_screen.dart';
import '../../presentation/screens/inventory/product_list_screen.dart';
import '../../presentation/screens/inventory/product_detail_screen.dart';
import '../../presentation/screens/inventory/category_screen.dart';
import '../../presentation/screens/invoices/invoice_list_screen.dart';
import '../../presentation/screens/invoices/create_invoice_screen.dart';
import '../../presentation/screens/invoices/invoice_detail_screen.dart';
import '../../presentation/screens/expenses/expense_screen.dart';
import '../../presentation/screens/expenses/add_expense_screen.dart';
import '../../presentation/screens/reports/reports_screen.dart';
import '../../presentation/screens/reports/trial_balance_screen.dart';
import '../../presentation/screens/reports/profit_loss_screen.dart';
import '../../presentation/screens/reports/balance_sheet_screen.dart';
import '../../presentation/screens/ai/ai_chat_screen.dart';
import '../../presentation/screens/ai/ai_settings_screen.dart';
import '../../presentation/screens/settings/settings_screen.dart';
import '../../presentation/screens/settings/backup_screen.dart';
import '../../presentation/screens/settings/profile_screen.dart';
import '../../presentation/screens/settings/change_password_screen.dart';
import '../../presentation/screens/enterprise/company_screen.dart';
import '../../presentation/screens/enterprise/godown_screen.dart';
import '../../presentation/screens/enterprise/batch_screen.dart';
import '../../presentation/screens/enterprise/cost_center_screen.dart';
import '../../presentation/screens/enterprise/budget_screen.dart';
import '../../presentation/screens/enterprise/audit_log_screen.dart';
import '../../presentation/screens/enterprise/cheque_screen.dart';
import '../../presentation/screens/enterprise/tds_screen.dart';
import '../../presentation/screens/enterprise/gst_return_screen.dart';
import '../../presentation/screens/enterprise/pos_screen.dart';
import '../../presentation/screens/enterprise/bank_reconciliation_screen.dart';
import '../../presentation/screens/enterprise/enhanced_reports_screen.dart';
import '../../presentation/screens/enterprise/price_level_screen.dart';
import '../../presentation/screens/enterprise/bom_screen.dart';

class AppRoutes {
  static const String splash = '/';
  static const String login = '/login';
  static const String register = '/register';
  static const String home = '/home';
  static const String dashboard = '/dashboard';
  static const String chartOfAccounts = '/accounts';
  static const String createAccount = '/accounts/create';
  static const String vouchers = '/vouchers';
  static const String createVoucher = '/vouchers/create';
  static const String customers = '/customers';
  static const String customerDetail = '/customers/detail';
  static const String suppliers = '/suppliers';
  static const String supplierDetail = '/suppliers/detail';
  static const String products = '/products';
  static const String productDetail = '/products/detail';
  static const String categories = '/categories';
  static const String invoices = '/invoices';
  static const String createInvoice = '/invoices/create';
  static const String invoiceDetail = '/invoices/detail';
  static const String expenses = '/expenses';
  static const String addExpense = '/expenses/add';
  static const String reports = '/reports';
  static const String trialBalance = '/reports/trial-balance';
  static const String profitLoss = '/reports/profit-loss';
  static const String balanceSheet = '/reports/balance-sheet';
  static const String enhancedReports = '/reports/enhanced';
  static const String aiChat = '/ai/chat';
  static const String aiSettings = '/ai/settings';
  static const String settings = '/settings';
  static const String backup = '/settings/backup';
  static const String profile = '/settings/profile';
  static const String changePassword = '/settings/change-password';
  static const String companies = '/enterprise/companies';
  static const String godowns = '/enterprise/godowns';
  static const String batches = '/enterprise/batches';
  static const String costCenters = '/enterprise/cost-centers';
  static const String budgets = '/enterprise/budgets';
  static const String auditLogs = '/enterprise/audit-logs';
  static const String cheques = '/enterprise/cheques';
  static const String tds = '/enterprise/tds';
  static const String gstReturns = '/enterprise/gst-returns';
  static const String pos = '/enterprise/pos';
  static const String bankReconciliation = '/enterprise/bank-reconciliation';
  static const String priceLevels = '/enterprise/price-levels';
  static const String bom = '/enterprise/bom';

  static Route<dynamic> generateRoute(RouteSettings routeSettings) {
    switch (routeSettings.name) {
      case splash: return MaterialPageRoute(builder: (_) => const SplashScreen());
      case login: return MaterialPageRoute(builder: (_) => const LoginScreen());
      case register: return MaterialPageRoute(builder: (_) => const RegisterScreen());
      case home: return MaterialPageRoute(builder: (_) => const HomeScreen());
      case dashboard: return MaterialPageRoute(builder: (_) => const DashboardScreen());
      case chartOfAccounts: return MaterialPageRoute(builder: (_) => const ChartOfAccountsScreen());
      case createAccount: return MaterialPageRoute(builder: (_) => const CreateAccountScreen());
      case vouchers: return MaterialPageRoute(builder: (_) => const VoucherScreen());
      case createVoucher: return MaterialPageRoute(builder: (_) => const CreateVoucherScreen());
      case customers: return MaterialPageRoute(builder: (_) => const CustomerListScreen());
      case customerDetail: final id = routeSettings.arguments as int; return MaterialPageRoute(builder: (_) => CustomerDetailScreen(customerId: id));
      case suppliers: return MaterialPageRoute(builder: (_) => const SupplierListScreen());
      case supplierDetail: final id = routeSettings.arguments as int; return MaterialPageRoute(builder: (_) => SupplierDetailScreen(supplierId: id));
      case products: return MaterialPageRoute(builder: (_) => const ProductListScreen());
      case productDetail: final id = routeSettings.arguments as int; return MaterialPageRoute(builder: (_) => ProductDetailScreen(productId: id));
      case categories: return MaterialPageRoute(builder: (_) => const CategoryScreen());
      case invoices: return MaterialPageRoute(builder: (_) => const InvoiceListScreen());
      case createInvoice: return MaterialPageRoute(builder: (_) => const CreateInvoiceScreen());
      case invoiceDetail: final id = routeSettings.arguments as int; return MaterialPageRoute(builder: (_) => InvoiceDetailScreen(invoiceId: id));
      case expenses: return MaterialPageRoute(builder: (_) => const ExpenseScreen());
      case addExpense: return MaterialPageRoute(builder: (_) => const AddExpenseScreen());
      case reports: return MaterialPageRoute(builder: (_) => const ReportsScreen());
      case trialBalance: return MaterialPageRoute(builder: (_) => const TrialBalanceScreen());
      case profitLoss: return MaterialPageRoute(builder: (_) => const ProfitLossScreen());
      case balanceSheet: return MaterialPageRoute(builder: (_) => const BalanceSheetScreen());
      case enhancedReports: return MaterialPageRoute(builder: (_) => const EnhancedReportsScreen());
      case aiChat: return MaterialPageRoute(builder: (_) => const AIChatScreen());
      case aiSettings: return MaterialPageRoute(builder: (_) => const AISettingsScreen());
      case settings: return MaterialPageRoute(builder: (_) => const SettingsScreen());
      case backup: return MaterialPageRoute(builder: (_) => const BackupScreen());
      case profile: return MaterialPageRoute(builder: (_) => const ProfileScreen());
      case changePassword: return MaterialPageRoute(builder: (_) => const ChangePasswordScreen());
      case companies: return MaterialPageRoute(builder: (_) => const CompanyScreen());
      case godowns: return MaterialPageRoute(builder: (_) => const GodownScreen());
      case batches: return MaterialPageRoute(builder: (_) => const BatchScreen());
      case costCenters: return MaterialPageRoute(builder: (_) => const CostCenterScreen());
      case budgets: return MaterialPageRoute(builder: (_) => const BudgetScreen());
      case auditLogs: return MaterialPageRoute(builder: (_) => const AuditLogScreen());
      case cheques: return MaterialPageRoute(builder: (_) => const ChequeScreen());
      case tds: return MaterialPageRoute(builder: (_) => const TDSScreen());
      case gstReturns: return MaterialPageRoute(builder: (_) => const GSTReturnScreen());
      case pos: return MaterialPageRoute(builder: (_) => const POSScreen());
      case bankReconciliation: return MaterialPageRoute(builder: (_) => const BankReconciliationScreen());
      case priceLevels: return MaterialPageRoute(builder: (_) => const PriceLevelScreen());
      case bom: return MaterialPageRoute(builder: (_) => const BOMScreen());
      default: return MaterialPageRoute(builder: (_) => const SplashScreen());
    }
  }
}
